name: Docker Build and Push

on:
  workflow_call:
    inputs:
      platform:
        description: "The platform to build the Docker image for. Common values: linux/amd64, linux/arm64, linux/arm/v7"
        required: true
        type: string
      tags:
        description: "The tags to apply to the Docker image. Should be a multi-line string or comma-seperated."
        required: true
        type: string
      buildargs:
        description: "The build args to pass to Docker. Should be a multi-line string."
        required: false
        type: string
      context:
        description: 'Docker context. Defaults to "."'
        required: true
        type: string
        default: "."
      dockerfile:
        description: 'Full Dockerfile path. Defaults to "Dockerfile"'
        required: false
        type: string
        default: "Dockerfile"
      attest_id:
        description: 'Attestation ID. If provided, an artifact will be produced with the digest of the image, named with this ID.'
        required: false
        type: string
      push:
        description: 'Whether to push the image'
        required: true
        type: boolean
        default: true
    secrets:
      dockerhub_username:
        description: "DockerHub username"
        required: false
      dockerhub_password:
        description: "DockerHub password"
        required: false

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: DockerHub Login
        if: contains(inputs.tags, 'docker.io')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Github CR Login
        if: contains(inputs.tags, 'ghcr.io')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ inputs.tags }}
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platform }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: ${{ inputs.buildargs }}
          push: true
          provenance: mode=max
          sbom: true

      - name: Write Image Digest
        if: inputs.attest_id
        run: echo "${{ steps.build-push.outputs.digest }}" > ${{ runner.temp }}/digest.txt

      - name: Upload Image Digest
        if: inputs.attest_id
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.attest_id }}
          path: ${{ runner.temp }}/digest.txt
