name: Pre-Commit Update

on:
  workflow_call:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run pre-commit-update
        run: pipx run pre-commit-update

      - name: Create change hash
        id: hasher
        shell: bash
        run: echo "hash=$(sha256sum .pre-commit-config.yaml | head -c 8)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          branch: update/pre-commit-update-${{ steps.hasher.outputs.hash }}
          sign-commits: true
          title: Update Pre-Commit hooks
          commit-message: Update Pre-Commit hooks
          body: |
            Update versions of tools in pre-commit configs to latest version.
            Please verify the changes locally, as a pull request created by GitHub Actions cannot trigger workflows:

            ```bash
            git fetch
            git checkout update/pre-commit-update-${{ steps.hasher.outputs.hash }}
            git pull
            vtr pre-commit
            ```
          labels: dependencies
