name: PyPi Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install poetry/vscode-task-runner
        run: |
          pipx install poetry
          pipx install vscode-task-runner

      - name: Build
        run: vtr build

      - name: Get version
        id: project
        run: echo "version=$(poetry version --short)" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.project.outputs.version }}
          github_token: ${{ github.token }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.project.outputs.version }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pkg-dist
          path: dist/

  # publish:
  #   needs: build

  #   permissions:
  #     id-token: write

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: pkg-dist
  #         path: dist/

  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1