name: Python Test

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      pytest:
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry/vscode-task-runner
        run: |
          pipx install poetry
          pipx install vscode-task-runner

      - name: Setup Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: poetry

      - name: Cache Pre-Commit
        uses: NathanVaughn/actions-pre-commit-cache@main

      - name: Run Pre-Commit Checks
        run: vtr pre-commit --color=always --show-diff-on-failure

      - name: Run Tests
        if: inputs.pytest
        run: vtr tests
